<a href="https://colab.research.google.com/github/Weedmastercrucifer/Neural-Networks-and-Fuzzy-Logic/blob/main/Assignment1Details/Assignment1_Q7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt


Assignment 1 Q7

In [ ]:
data=pd.read_csv('/content/drive/MyDrive/Assignment1NNFL/Copy of data_q6_q7.txt',delimiter="\t",error_bad_lines=False)
#removing bad lines from the dataset

b'Skipping line 8: expected 8 fields, saw 10\nSkipping line 36: expected 8 fields, saw 10\nSkipping line 61: expected 8 fields, saw 9\nSkipping line 69: expected 8 fields, saw 9\nSkipping line 107: expected 8 fields, saw 9\nSkipping line 136: expected 8 fields, saw 9\nSkipping line 170: expected 8 fields, saw 9\nSkipping line 171: expected 8 fields, saw 9\nSkipping line 173: expected 8 fields, saw 9\nSkipping line 202: expected 8 fields, saw 9\nSkipping line 204: expected 8 fields, saw 9\n'


In [ ]:
data


15.26  14.84   0.871  5.763  3.312  2.221   5.22  1
0    14.88  14.57  0.8811  5.554  3.333  1.018  4.956  1
1    14.29  14.09  0.9050  5.291  3.337  2.699  4.825  1
2    13.84  13.94  0.8955  5.324  3.379  2.259  4.805  1
3    16.14  14.99  0.9034  5.658  3.562  1.355  5.175  1
4    14.38  14.21  0.8951  5.386  3.312  2.462  4.956  1
..     ...    ...     ...    ...    ...    ...    ... ..
193  12.19  13.20  0.8783  5.137  2.981  3.631  4.870  3
194  11.23  12.88  0.8511  5.140  2.795  4.325  5.003  3
195  13.20  13.66  0.8883  5.236  3.232  8.315  5.056  3
196  11.84  13.21  0.8521  5.175  2.836  3.598  5.044  3
197  12.30  13.34  0.8684  5.243  2.974  5.637  5.063  3

[198 rows x 8 columns]

In [ ]:
data.describe()

15.26       14.84       0.871  ...       2.221        5.22           1
count  198.000000  198.000000  198.000000  ...  198.000000  198.000000  198.000000
mean    14.917020   14.594596    0.870810  ...    3.706683    5.421667    2.000000
std      2.927276    1.313651    0.023379  ...    1.471047    0.493759    0.812341
min     10.590000   12.410000    0.808100  ...    0.765100    4.519000    1.000000
25%     12.315000   13.470000    0.856900  ...    2.600250    5.046000    1.000000
50%     14.405000   14.360000    0.873450  ...    3.634500    5.229500    2.000000
75%     17.502500   15.827500    0.886900  ...    4.812000    5.879000    3.000000
max     21.180000   17.250000    0.918300  ...    8.315000    6.550000    3.000000

[8 rows x 8 columns]

In [ ]:
data.iloc[:,0:7]=(data.iloc[:,0:7]-(data.iloc[:,0:7]).min())/((data.iloc[:,0:7]).max()-(data.iloc[:,0:7]).min())


In [ ]:
data

15.26     14.84     0.871     5.763     3.312     2.221      5.22  1
0    0.405099  0.446281  0.662432  0.368806  0.501069  0.033497  0.215165  1
1    0.349386  0.347107  0.879310  0.220721  0.503920  0.256149  0.150665  1
2    0.306893  0.316116  0.793103  0.239302  0.533856  0.197870  0.140817  1
3    0.524079  0.533058  0.864791  0.427365  0.664291  0.078133  0.322994  1
4    0.357885  0.371901  0.789474  0.274212  0.486101  0.224758  0.215165  1
..        ...       ...       ...       ...       ...       ...       ... ..
193  0.151086  0.163223  0.637024  0.134009  0.250178  0.379594  0.172821  3
194  0.060434  0.097107  0.390200  0.135698  0.117605  0.471516  0.238306  3
195  0.246459  0.258264  0.727768  0.189752  0.429081  1.000000  0.264402  3
196  0.118036  0.165289  0.399274  0.155405  0.146828  0.375224  0.258493  3
197  0.161473  0.192149  0.547187  0.193694  0.245189  0.645293  0.267848  3

[198 rows x 8 columns]

In [ ]:
data=data.sample(frac=1, random_state=50)#randomising data


In [ ]:
data.head()

15.26     14.84     0.871     5.763     3.312     2.221      5.22  1
170  0.077432  0.111570  0.434664  0.107545  0.103350  0.555226  0.150665  3
24   0.229462  0.278926  0.508167  0.279279  0.282252  0.345422  0.150665  1
151  0.109537  0.229339  0.000907  0.306869  0.034212  0.478536  0.389463  3
20   0.499528  0.514463  0.823049  0.404842  0.625089  0.000000  0.281635  1
54   0.408876  0.417355  0.839383  0.273086  0.557377  0.049921  0.280158  1

In [ ]:
data.dtypes

15.26    float64
14.84    float64
0.871    float64
5.763    float64
3.312    float64
2.221    float64
5.22     float64
1          int64
dtype: object

In [ ]:
data['1'].nunique()#number of classes to be classified

3

In [ ]:
data=np.array(data)

Preparing training data for 1 v 1 multiclass logistic regression

In [ ]:
def split_trainset(train): 
  train1, train2, train3 = [], [], []
  for row in train:
    if row[-1] == 1:
          train1.append(row)
          train2.append(row)

    elif row[-1] == 2:
          train1.append(row)
          train3.append(row)

    elif row[-1] == 3:
          train2.append(row)
          train3.append(row) 
  train1, train2, train3 = np.array(train1), np.array(train2), np.array(train3) 

  for row in train1:
      row[-1] = 0 if row[-1] == 1 else 1

  for row in train2:
      row[-1] = 0 if row[-1] == 1 else 1

  for row in train3:
      row[-1] = 0 if row[-1] == 2 else 1 
  return train1,train2,train3    


In [ ]:
def partition(vector, fold, k):
    size = vector.shape[0]
    start =round((size/k)*fold)
    end = round((size/k)*(fold+1))
    validation = vector[start:end]
    training = np.concatenate((vector[:start], vector[end:])) 
    print(training.shape)
    print(validation.shape)
    return training, validation

In [ ]:
def sas(y_pred, y_test):
    tp = tn = fp = fn = 0 #initialising true positive, true negative, false positive and false negative
    m = y_test.shape[0]
    for i in range(m):
        if y_pred[i] == 1:
            if y_test[i] == 1:
                tp+=1
            else:
                fp+=1
        elif y_pred[i] == 0:
            if y_test[i] == 0:
                tn+=1
            else:
                fn+=1
    se = tp/(tp+fn)
    sp = tn/(tn+fp)
    ac = (tn+tp)/m
    print("Sensitivity: {0}, Specificity: {1} and Accuracy: {2}".format(se,sp,ac)) 
    return se,sp,ac

In [ ]:
#sigmoid function
def sigmoid(x): 
 return 1.0/(1 + np.exp(-x))

In [ ]:
#cost for an observation
def logistic_loss(y_train,y_pred):
  loss = -y_train * np.log(y_pred)
  loss -= (1-y_train)*np.log(1-y_pred)
  return loss

In [ ]:
def cost_function_no_regu(X,y,w):
  hypothesis=sigmoid(np.dot(X,w.T).astype(float))
  J=(1/(2*len(y)))*np.sum(logistic_loss(y,hypothesis))
  return J

In [ ]:
def batch_gradient_descent_no_regu(X,y,w,alpha,iters):
  cost_hist=np.zeros(iters)#initialising cost function for each iteration 
  w_hist=np.zeros((iters,8))#for storing weight values at each iteration 
  for t in range(iters): 
    
    hypothesis=sigmoid(np.dot(X,w.T).astype(float))
    w=w-(alpha/len(y))*(np.dot(hypothesis-y,X))#updating the weight value
    w_hist[t]=w
    cost_hist[t]=cost_function_no_regu(X,y,w)#storing the cost function value for that iteration
  minpos=np.argmin(cost_hist)
  w_best=w_hist[minpos]  
  return w_best 

In [ ]:
def stochastic_gradient_descent_no_regu(X,y,w,alpha,iters):
  cost_hist=np.zeros(iters)#initialising cost function for each iteration 
  w_hist=np.zeros((iters,8))#for storing weight values at each iteration 
  for t in range(iters):
    index=np.random.randint(len(y))#randomly selecting an index from the dataset
    Ind_X=X[index:index+1]#selecting features of that index
    Ind_Y=y[index:index+1]#selecting the true output of that index 
    w=w-alpha*(Ind_X.T.dot(sigmoid(np.dot(Ind_X,w.T).astype(float))-Ind_Y))#updating weight value
    w_hist[t]=w
    cost_hist[t]=cost_function_no_regu(X,y,w)
  minpos=np.argmin(cost_hist)
  w_best=w_hist[minpos]  
  return w_best

In [ ]:
def minibatch_gradient_descent_no_regu(X,y,w,alpha,iters,batch_size):
  cost_hist=np.zeros(iters)#initialising cost function for each iteration 
  w_hist=np.zeros((iters,8))#for storing weight values at each iteration
  for t in range(iters):
    index=np.random.randint(len(y))#randomly selecting an index from the dataset
    Ind_X=X[index:index+batch_size]#selecting features from that index to index+batchsize-1
    Ind_Y=y[index:index+batch_size]#selecting the true outputs from that index to index+batch_size-1
    w=w-(alpha/batch_size)*(Ind_X.T.dot(sigmoid(np.dot(Ind_X,w.T).astype(float))-Ind_Y))#updating weight value
    w_hist[t]=w
    cost_hist[t]=cost_function_no_regu(X,y,w)
  minpos=np.argmin(cost_hist)
  w_best=w_hist[minpos]  
  return w_best

In [ ]:
def cost_function_L2_regu(X,y,w,L2): 
  hypothesis=sigmoid(np.dot(X,w.T).astype(float))
  J=(1/(2*len(y)))*np.sum(logistic_loss(y,hypothesis))+((L2/(2*len(y)))*np.sum(w**2)) 
  return J

In [ ]:
def batch_gradient_descent_L2_regu(X,y,w,alpha,iters,Lambda_):
  cost_hist=np.zeros(iters)#storing cost function value of each iteration
  w_hist=np.zeros((iters,8))#for storing weight values at each iteration
  for t in range(iters): 
    hypothesis=sigmoid(np.dot(X,w.T).astype(float)) 
    w=(w*(1-(alpha*Lambda_)))-(alpha/len(y))*(np.dot(hypothesis-y,X))#updating the weight value
    w_hist[t]=w
    cost_hist[t]=cost_function_L2_regu(X,y,w,Lambda_)#storing the cost function value for that iteration
  minpos=np.argmin(cost_hist)
  w_best=w_hist[minpos]  
  return w_best

In [ ]:
def stochastic_gradient_descent_L2_regu(X,y,w,alpha,iters,Lambda_):
  cost_hist=np.zeros(iters)#initialising cost function for each iteration 
  w_hist=np.zeros((iters,8))#for storing weight values at each iteration 
  for t in range(iters):
    index=np.random.randint(len(y))#randomly selecting an index from the dataset
    Ind_X=X[index:index+1]#selecting features of that index
    Ind_Y=y[index:index+1]#selecting the true output of that index 
    w=(w*(1-(alpha*Lambda_)))-alpha*(Ind_X.T.dot(sigmoid(np.dot(Ind_X,w.T).astype(float))-Ind_Y))#updating weight value
    w_hist[t]=w
    cost_hist[t]=cost_function_L2_regu(X,y,w,Lambda_)
  minpos=np.argmin(cost_hist)
  w_best=w_hist[minpos]  
  return w_best

In [ ]:
def minibatch_gradient_descent_L2_regu(X,y,w,alpha,iters,batch_size,Lambda_):
  cost_hist=np.zeros(iters)#initialising cost function for each iteration 
  w_hist=np.zeros((iters,8))#for storing weight values at each iteration
  for t in range(iters):
    index=np.random.randint(len(y))#randomly selecting an index from the dataset
    Ind_X=X[index:index+batch_size]#selecting features from that index to index+batchsize-1
    Ind_Y=y[index:index+batch_size]#selecting the true outputs from that index to index+batch_size-1
    w=(w*(1-(alpha*Lambda_)))-(alpha/batch_size)*(Ind_X.T.dot(sigmoid(np.dot(Ind_X,w.T).astype(float))-Ind_Y))#updating weight value
    w_hist[t]=w
    cost_hist[t]=cost_function_L2_regu(X,y,w,Lambda_)
  minpos=np.argmin(cost_hist)
  w_best=w_hist[minpos]  
  return w_best

In [ ]:
def cost_function_L1_regu(X,y,w,L1): 
  hypothesis=sigmoid(np.dot(X,w.T).astype(float))  
  J=(1/(2*len(y)))*np.sum(logistic_loss(y,hypothesis))+((L1/(2*len(y)))*np.sum(abs(w))) 
  return J

In [ ]:
def batch_gradient_descent_L1_regu(X,y,w,alpha,iters,Lambda_): 
  cost_hist=np.zeros(iters)#storing cost function value of each iteration
  w_hist=np.zeros((iters,8))#for storing weight values at each iteration
  for t in range(iters): 
    hypothesis=sigmoid(np.dot(X,w.T).astype(float)) 
    w=w-((alpha*Lambda_)/2)*np.sign(w)-(alpha/len(y))*(np.dot(hypothesis-y,X))#updating the weight value 
    w_hist[t]=w
    cost_hist[t]=cost_function_L1_regu(X,y,w,Lambda_)#storing the cost function value for that iteration
  minpos=np.argmin(cost_hist)
  w_best=w_hist[minpos]  
  return w_best

In [ ]:
def stochastic_gradient_descent_L1_regu(X,y,w,alpha,iters,Lambda_):
  cost_hist=np.zeros(iters)#initialising cost function for each iteration 
  w_hist=np.zeros((iters,8))#for storing weight values at each iteration 
  for t in range(iters):
    index=np.random.randint(len(y))#randomly selecting an index from the dataset
    Ind_X=X[index:index+1]#selecting features of that index
    Ind_Y=y[index:index+1]#selecting the true output of that index 
    w=w-((alpha*Lambda_)/2)*np.sign(w) -alpha*(Ind_X.T.dot(sigmoid(np.dot(Ind_X,w.T).astype(float))-Ind_Y))#updating weight value 
    w_hist[t]=w
    cost_hist[t]=cost_function_L1_regu(X,y,w,Lambda_)#storing the cost function value for that iteration
  minpos=np.argmin(cost_hist)
  w_best=w_hist[minpos]  
  return w_best

In [ ]:
def minibatch_gradient_descent_L1_regu(X,y,w,alpha,iters,batch_size,Lambda_):
  cost_hist=np.zeros(iters)#initialising cost function for each iteration 
  w_hist=np.zeros((iters,8))#for storing weight values at each iteration
  for t in range(iters):
    index=np.random.randint(len(y))#randomly selecting an index from the dataset
    Ind_X=X[index:index+batch_size]#selecting features from that index to index+batchsize-1
    Ind_Y=y[index:index+batch_size]#selecting the true outputs from that index to index+batch_size-1 
    w=w-((alpha*Lambda_)/2)*np.sign(w)-(alpha/batch_size)*(Ind_X.T.dot(sigmoid(np.dot(Ind_X,w.T).astype(float))-Ind_Y))#updating weight value 
    w_hist[t]=w
    cost_hist[t]=cost_function_L1_regu(X,y,w,Lambda_)#storing the cost function value for that iteration
  minpos=np.argmin(cost_hist)
  w_best=w_hist[minpos]  
  return w_best

In [ ]:
alpha=0.9
iters=15000
Lambda_=0.005 


Initialising weights for all 9 models for 1v1 multiclass logistic regression

In [ ]:
weights_batch_no_regu=np.random.rand(3,8)
weights_stoch_no_regu=np.random.rand(3,8)
weights_mini_no_regu=np.random.rand(3,8) 
weights_batch_L2_regu=np.random.rand(3,8)
weights_stoch_L2_regu=np.random.rand(3,8)
weights_mini_L2_regu=np.random.rand(3,8)  
weights_batch_L1_regu=np.random.rand(3,8)
weights_stoch_L1_regu=np.random.rand(3,8)
weights_mini_L1_regu=np.random.rand(3,8)


Training of weights for all 9 models of 1v1 multiclass logistic regression

Initialsing confusion matrixes for the 9 models validation for fine tuning
and test for accuracy





In [ ]:
confusion_matrix_batch_validation_no_regu = np.zeros((3,3))
confusion_matrix_batch_test_no_regu = np.zeros((3,3))
confusion_matrix_stoch_validation_no_regu = np.zeros((3,3))
confusion_matrix_stoch_test_no_regu = np.zeros((3,3))
confusion_matrix_mini_validation_no_regu = np.zeros((3,3))
confusion_matrix_mini_test_no_regu = np.zeros((3,3))
confusion_matrix_batch_validation_L2_regu = np.zeros((3,3))
confusion_matrix_batch_test_L2_regu = np.zeros((3,3))
confusion_matrix_stoch_validation_L2_regu = np.zeros((3,3))
confusion_matrix_stoch_test_L2_regu = np.zeros((3,3))
confusion_matrix_mini_validation_L2_regu = np.zeros((3,3))
confusion_matrix_mini_test_L2_regu = np.zeros((3,3))
confusion_matrix_batch_validation_L1_regu = np.zeros((3,3))
confusion_matrix_batch_test_L1_regu = np.zeros((3,3))
confusion_matrix_stoch_validation_L1_regu = np.zeros((3,3))
confusion_matrix_stoch_test_L1_regu = np.zeros((3,3))
confusion_matrix_mini_validation_L1_regu = np.zeros((3,3))
confusion_matrix_mini_test_L1_regu = np.zeros((3,3))

Prediction on validate and test for 1v1 multiclass classification

In [ ]:
def predict(test,weights,confusion_matrix): 
  
  for row in test:

      predicted = 0
      h = []
      
      for i in range(3):
          h_ = np.dot(row[:-1], weights[i]) 
          h_ = sigmoid(h_)
          h.append(round(h_))

      if h[0] == 0 and h[1] == 0: predicted = 1
      if h[0] == 1 and h[2] == 0: predicted = 2
      if h[1] == 1 and h[2] == 1: predicted = 3

      confusion_matrix[int(row[-1])-1, predicted-1] += 1

  c1 = confusion_matrix[0,0]/np.sum(confusion_matrix[0])
  c2 = confusion_matrix[1,1]/np.sum(confusion_matrix[1])
  c3 = confusion_matrix[2,2]/np.sum(confusion_matrix[2])
  d1=((confusion_matrix[1,1]+confusion_matrix[1,2]+confusion_matrix[2,1]+confusion_matrix[2,2])/
      (np.sum(confusion_matrix[1])+np.sum(confusion_matrix[2]))) 
  d2=((confusion_matrix[0,0]+confusion_matrix[0,2]+confusion_matrix[2,0]+confusion_matrix[2,2])/
      (np.sum(confusion_matrix[0])+np.sum(confusion_matrix[2]))) 
  d3=((confusion_matrix[0,0]+confusion_matrix[0,1]+confusion_matrix[1,0]+confusion_matrix[1,1])/
      (np.sum(confusion_matrix[0])+np.sum(confusion_matrix[1])))  
  
  total_accuracy = (confusion_matrix[0,0] + confusion_matrix[1,1] + confusion_matrix[2,2])/np.sum(confusion_matrix)

  print("Total accuracy: ", total_accuracy)
  print("Class 1 accuracy: ", c1)
  print("Class 2 accuracy: ", c2)
  print("Class 3 accuracy: ", c3)
  print(confusion_matrix) 
  return c1,c2,c3,d1,d2,d3 

In [ ]:
def Cross_Validation(w, k, examples, c,alpha,iters,Lambda_,confusion_matrix):
    train_folds_score = []
    test_folds_score = [] 
    m=examples.shape[0]
    pp=np.ones([m,1])
    examples=np.append(pp,examples,axis=1)
  
    #1st model 
    if (c==1):
      #for batch gradient descent with no regularization
      for fold in range(0, k):
            training_set, test_set = partition(examples, fold, k)
            train1,train2,train3=split_trainset(training_set) 
            X_train1=train1[:,0:8]
            y_train1=train1[:,8]
            X_train2=train2[:,0:8]
            y_train2=train2[:,8]
            X_train3=train3[:,0:8]
            y_train3=train3[:,8] 
            w[0], w[1], w[2]=(
            batch_gradient_descent_no_regu(X_train1,y_train1,w[0],alpha,iters), 
            batch_gradient_descent_no_regu(X_train2,y_train2,w[1],alpha,iters),
            batch_gradient_descent_no_regu(X_train3,y_train3,w[2],alpha,iters)) 
            #predict(training_set,weights_batch_no_regu,confusion_matrix_batch)
            sens1,sens2,sens3,spec1,spec2,spec3=predict(test_set,w,confusion_matrix)   
            print("Sensitivity of Class 1",sens1)
            print("Specificity of Class 1",spec1) 
            print("Sensitivity of Class 2",sens2)
            print("Specificity of Class 2",spec2) 
            print("Sensitivity of Class 3",sens3)
            print("Specificity of Class 3",spec3)
            confusion_matrix=np.zeros((3,3))

    elif (c==2):
      #for stochastic gradient descent with no regularization 
      #2nd model
      for fold in range(0, k):
            training_set, test_set = partition(examples, fold, k)
            train1,train2,train3=split_trainset(training_set) 
            X_train1=train1[:,0:8]
            y_train1=train1[:,8]
            X_train2=train2[:,0:8]
            y_train2=train2[:,8]
            X_train3=train3[:,0:8]
            y_train3=train3[:,8] 
            w[0], w[1], w[2]=(
            stochastic_gradient_descent_no_regu(X_train1,y_train1,w[0],alpha,iters), 
            stochastic_gradient_descent_no_regu(X_train2,y_train2,w[1],alpha,iters),
            stochastic_gradient_descent_no_regu(X_train3,y_train3,w[2],alpha,iters))  
            sens1,sens2,sens3,spec1,spec2,spec3=predict(test_set,w,confusion_matrix)   
            print("Sensitivity of Class 1",sens1)
            print("Specificity of Class 1",spec1) 
            print("Sensitivity of Class 2",sens2)
            print("Specificity of Class 2",spec2) 
            print("Sensitivity of Class 3",sens3)
            print("Specificity of Class 3",spec3)
            confusion_matrix=np.zeros((3,3))

    elif (c==3):
        #for minibatch descent with no regularization
        #3rd model
        for fold in range(0, k):
            training_set, test_set = partition(examples, fold, k)
            train1,train2,train3=split_trainset(training_set) 
            X_train1=train1[:,0:8]
            y_train1=train1[:,8]
            X_train2=train2[:,0:8]
            y_train2=train2[:,8]
            X_train3=train3[:,0:8]
            y_train3=train3[:,8]
            w[0], w[1], w[2]=(
            minibatch_gradient_descent_no_regu(X_train1,y_train1,w[0],alpha,iters,10), 
            minibatch_gradient_descent_no_regu(X_train2,y_train2,w[1],alpha,iters,10),
            minibatch_gradient_descent_no_regu(X_train3,y_train3,w[2],alpha,iters,10))
            sens1,sens2,sens3,spec1,spec2,spec3=predict(test_set,w,confusion_matrix)   
            print("Sensitivity of Class 1",sens1)
            print("Specificity of Class 1",spec1) 
            print("Sensitivity of Class 2",sens2)
            print("Specificity of Class 2",spec2) 
            print("Sensitivity of Class 3",sens3)
            print("Specificity of Class 3",spec3)
            confusion_matrix=np.zeros((3,3))


    elif (c==4):
        #for batch descent with L2 regularization
        #4th model
        for fold in range(0, k):
            training_set, test_set = partition(examples, fold, k)
            train1,train2,train3=split_trainset(training_set) 
            X_train1=train1[:,0:8]
            y_train1=train1[:,8]
            X_train2=train2[:,0:8]
            y_train2=train2[:,8]
            X_train3=train3[:,0:8]
            y_train3=train3[:,8]
            w[0], w[1], w[2]=(
            batch_gradient_descent_L2_regu(X_train1,y_train1,w[0],alpha,iters,Lambda_), 
            batch_gradient_descent_L2_regu(X_train2,y_train2,w[1],alpha,iters,Lambda_),
            batch_gradient_descent_L2_regu(X_train3,y_train3,w[2],alpha,iters,Lambda_)) 
            sens1,sens2,sens3,spec1,spec2,spec3=predict(test_set,w,confusion_matrix)   
            print("Sensitivity of Class 1",sens1)
            print("Specificity of Class 1",spec1) 
            print("Sensitivity of Class 2",sens2)
            print("Specificity of Class 2",spec2) 
            print("Sensitivity of Class 3",sens3)
            print("Specificity of Class 3",spec3)
            confusion_matrix=np.zeros((3,3))

    elif (c==5):
        #for stochastic descent with L2 regularization
        #5th model
        for fold in range(0, k):
            training_set, test_set = partition(examples, fold, k)
            train1,train2,train3=split_trainset(training_set) 
            X_train1=train1[:,0:8]
            y_train1=train1[:,8]
            X_train2=train2[:,0:8]
            y_train2=train2[:,8]
            X_train3=train3[:,0:8]
            y_train3=train3[:,8]
            w[0], w[1], w[2]=(
            stochastic_gradient_descent_L2_regu(X_train1,y_train1,w[0],alpha,iters,Lambda_), 
            stochastic_gradient_descent_L2_regu(X_train2,y_train2,w[1],alpha,iters,Lambda_),
            stochastic_gradient_descent_L2_regu(X_train3,y_train3,w[2],alpha,iters,Lambda_))
            sens1,sens2,sens3,spec1,spec2,spec3=predict(test_set,w,confusion_matrix)   
            print("Sensitivity of Class 1",sens1)
            print("Specificity of Class 1",spec1) 
            print("Sensitivity of Class 2",sens2)
            print("Specificity of Class 2",spec2) 
            print("Sensitivity of Class 3",sens3)
            print("Specificity of Class 3",spec3) 
            confusion_matrix=np.zeros((3,3))


    elif (c==6):
        #for minibatch descent with L2 regularization
        #6th model
        for fold in range(0, k):
            training_set, test_set = partition(examples, fold, k)
            train1,train2,train3=split_trainset(training_set) 
            X_train1=train1[:,0:8]
            y_train1=train1[:,8]
            X_train2=train2[:,0:8]
            y_train2=train2[:,8]
            X_train3=train3[:,0:8]
            y_train3=train3[:,8]
            w[0], w[1], w[2]=(
            minibatch_gradient_descent_L2_regu(X_train1,y_train1,w[0],alpha,iters,10,Lambda_), 
            minibatch_gradient_descent_L2_regu(X_train2,y_train2,w[1],alpha,iters,10,Lambda_),
            minibatch_gradient_descent_L2_regu(X_train3,y_train3,w[2],alpha,iters,10,Lambda_))
            sens1,sens2,sens3,spec1,spec2,spec3=predict(test_set,w,confusion_matrix)   
            print("Sensitivity of Class 1",sens1)
            print("Specificity of Class 1",spec1) 
            print("Sensitivity of Class 2",sens2)
            print("Specificity of Class 2",spec2) 
            print("Sensitivity of Class 3",sens3)
            print("Specificity of Class 3",spec3) 
            confusion_matrix=np.zeros((3,3)) 

    elif (c==7):
        #for batch descent with L1 regularization
        #7th model
        for fold in range(0, k):
            training_set, test_set = partition(examples, fold, k)
            train1,train2,train3=split_trainset(training_set) 
            X_train1=train1[:,0:8]
            y_train1=train1[:,8]
            X_train2=train2[:,0:8]
            y_train2=train2[:,8]
            X_train3=train3[:,0:8]
            y_train3=train3[:,8]
            w[0], w[1], w[2]=(
            batch_gradient_descent_L1_regu(X_train1,y_train1,w[0],alpha,iters,Lambda_), 
            batch_gradient_descent_L1_regu(X_train2,y_train2,w[1],alpha,iters,Lambda_),
            batch_gradient_descent_L1_regu(X_train3,y_train3,w[2],alpha,iters,Lambda_))
            sens1,sens2,sens3,spec1,spec2,spec3=predict(test_set,w,confusion_matrix)   
            print("Sensitivity of Class 1",sens1)
            print("Specificity of Class 1",spec1) 
            print("Sensitivity of Class 2",sens2)
            print("Specificity of Class 2",spec2) 
            print("Sensitivity of Class 3",sens3)
            print("Specificity of Class 3",spec3)
            confusion_matrix=np.zeros((3,3)) 

    elif (c==8):
        #for stochastic descent with L1 regularization
        #8th model
        for fold in range(0, k):
            training_set, test_set = partition(examples, fold, k)
            train1,train2,train3=split_trainset(training_set) 
            X_train1=train1[:,0:8]
            y_train1=train1[:,8]
            X_train2=train2[:,0:8]
            y_train2=train2[:,8]
            X_train3=train3[:,0:8]
            y_train3=train3[:,8]
            w[0], w[1], w[2]=(
            stochastic_gradient_descent_L1_regu(X_train1,y_train1,w[0],alpha,iters,Lambda_), 
            stochastic_gradient_descent_L1_regu(X_train2,y_train2,w[1],alpha,iters,Lambda_),
            stochastic_gradient_descent_L1_regu(X_train3,y_train3,w[2],alpha,iters,Lambda_))
            sens1,sens2,sens3,spec1,spec2,spec3=predict(test_set,w,confusion_matrix)   
            print("Sensitivity of Class 1",sens1)
            print("Specificity of Class 1",spec1) 
            print("Sensitivity of Class 2",sens2)
            print("Specificity of Class 2",spec2) 
            print("Sensitivity of Class 3",sens3)
            print("Specificity of Class 3",spec3) 
            confusion_matrix=np.zeros((3,3))

    elif (c==9):
        #for minibatch descent with L1 regularization
        #8th model
        for fold in range(0, k):
            training_set, test_set = partition(examples, fold, k)
            train1,train2,train3=split_trainset(training_set) 
            X_train1=train1[:,0:8]
            y_train1=train1[:,8]
            X_train2=train2[:,0:8]
            y_train2=train2[:,8]
            X_train3=train3[:,0:8]
            y_train3=train3[:,8]
            w[0], w[1], w[2]=(
            minibatch_gradient_descent_L1_regu(X_train1,y_train1,w[0],alpha,iters,10,Lambda_), 
            minibatch_gradient_descent_L1_regu(X_train2,y_train2,w[1],alpha,iters,10,Lambda_),
            minibatch_gradient_descent_L1_regu(X_train3,y_train3,w[2],alpha,iters,10,Lambda_))
            sens1,sens2,sens3,spec1,spec2,spec3=predict(test_set,w,confusion_matrix)   
            print("Sensitivity of Class 1",sens1)
            print("Specificity of Class 1",spec1) 
            print("Sensitivity of Class 2",sens2)
            print("Specificity of Class 2",spec2) 
            print("Sensitivity of Class 3",sens3)
            print("Specificity of Class 3",spec3) 
            confusion_matrix=np.zeros((3,3))

In [ ]:
Cross_Validation(weights_batch_no_regu, 5, data, 1,alpha,iters,Lambda_,confusion_matrix_batch_test_no_regu)

(158, 9)
(40, 9)
Total accuracy:  0.975
Class 1 accuracy:  0.9090909090909091
Class 2 accuracy:  1.0
Class 3 accuracy:  1.0
[[10.  1.  0.]
 [ 0. 10.  0.]
 [ 0.  0. 19.]]
Sensitivity of Class 1 0.9090909090909091
Specificity of Class 1 1.0
Sensitivity of Class 2 1.0
Specificity of Class 2 0.9666666666666667
Sensitivity of Class 3 1.0
Specificity of Class 3 1.0
(159, 9)
(39, 9)
Total accuracy:  0.9743589743589743
Class 1 accuracy:  0.875
Class 2 accuracy:  1.0
Class 3 accuracy:  1.0
[[ 7.  0.  1.]
 [ 0. 18.  0.]
 [ 0.  0. 13.]]
Sensitivity of Class 1 0.875
Specificity of Class 1 1.0
Sensitivity of Class 2 1.0
Specificity of Class 2 1.0
Sensitivity of Class 3 1.0
Specificity of Class 3 0.9615384615384616
(158, 9)
(40, 9)
Total accuracy:  0.95
Class 1 accuracy:  1.0
Class 2 accuracy:  0.9166666666666666
Class 3 accuracy:  0.8888888888888888
[[19.  0.  0.]
 [ 1. 11.  0.]
 [ 1.  0.  8.]]
Sensitivity of Class 1 1.0
Specificity of Class 1 0.9047619047619048
Sensitivity of Class 2 0.91666666666

In [ ]:
Cross_Validation(weights_stoch_no_regu, 5, data, 2,alpha,iters,Lambda_,confusion_matrix_stoch_test_no_regu)

(158, 9)
(40, 9)
Total accuracy:  0.975
Class 1 accuracy:  0.9090909090909091
Class 2 accuracy:  1.0
Class 3 accuracy:  1.0
[[10.  1.  0.]
 [ 0. 10.  0.]
 [ 0.  0. 19.]]
Sensitivity of Class 1 0.9090909090909091
Specificity of Class 1 1.0
Sensitivity of Class 2 1.0
Specificity of Class 2 0.9666666666666667
Sensitivity of Class 3 1.0
Specificity of Class 3 1.0
(159, 9)
(39, 9)
Total accuracy:  0.9743589743589743
Class 1 accuracy:  0.875
Class 2 accuracy:  1.0
Class 3 accuracy:  1.0
[[ 7.  0.  1.]
 [ 0. 18.  0.]
 [ 0.  0. 13.]]
Sensitivity of Class 1 0.875
Specificity of Class 1 1.0
Sensitivity of Class 2 1.0
Specificity of Class 2 1.0
Sensitivity of Class 3 1.0
Specificity of Class 3 0.9615384615384616
(158, 9)
(40, 9)
Total accuracy:  0.95
Class 1 accuracy:  1.0
Class 2 accuracy:  0.9166666666666666
Class 3 accuracy:  0.8888888888888888
[[19.  0.  0.]
 [ 1. 11.  0.]
 [ 1.  0.  8.]]
Sensitivity of Class 1 1.0
Specificity of Class 1 0.9047619047619048
Sensitivity of Class 2 0.91666666666

In [ ]:
Cross_Validation(weights_mini_no_regu, 5, data, 3,alpha,iters,Lambda_,confusion_matrix_mini_test_no_regu)

(158, 9)
(40, 9)
Total accuracy:  0.975
Class 1 accuracy:  0.9090909090909091
Class 2 accuracy:  1.0
Class 3 accuracy:  1.0
[[10.  1.  0.]
 [ 0. 10.  0.]
 [ 0.  0. 19.]]
Sensitivity of Class 1 0.9090909090909091
Specificity of Class 1 1.0
Sensitivity of Class 2 1.0
Specificity of Class 2 0.9666666666666667
Sensitivity of Class 3 1.0
Specificity of Class 3 1.0
(159, 9)
(39, 9)
Total accuracy:  0.9743589743589743
Class 1 accuracy:  0.875
Class 2 accuracy:  1.0
Class 3 accuracy:  1.0
[[ 7.  0.  1.]
 [ 0. 18.  0.]
 [ 0.  0. 13.]]
Sensitivity of Class 1 0.875
Specificity of Class 1 1.0
Sensitivity of Class 2 1.0
Specificity of Class 2 1.0
Sensitivity of Class 3 1.0
Specificity of Class 3 0.9615384615384616
(158, 9)
(40, 9)
Total accuracy:  0.95
Class 1 accuracy:  1.0
Class 2 accuracy:  0.9166666666666666
Class 3 accuracy:  0.8888888888888888
[[19.  0.  0.]
 [ 1. 11.  0.]
 [ 1.  0.  8.]]
Sensitivity of Class 1 1.0
Specificity of Class 1 0.9047619047619048
Sensitivity of Class 2 0.91666666666

In [ ]:
Cross_Validation(weights_batch_L2_regu, 5, data, 4,alpha,iters,Lambda_,confusion_matrix_batch_test_L2_regu)

(158, 9)
(40, 9)
Total accuracy:  0.95
Class 1 accuracy:  0.9090909090909091
Class 2 accuracy:  1.0
Class 3 accuracy:  0.9473684210526315
[[10.  1.  0.]
 [ 0. 10.  0.]
 [ 1.  0. 18.]]
Sensitivity of Class 1 0.9090909090909091
Specificity of Class 1 0.9655172413793104
Sensitivity of Class 2 1.0
Specificity of Class 2 0.9666666666666667
Sensitivity of Class 3 0.9473684210526315
Specificity of Class 3 1.0
(159, 9)
(39, 9)
Total accuracy:  0.9743589743589743
Class 1 accuracy:  0.875
Class 2 accuracy:  1.0
Class 3 accuracy:  1.0
[[ 7.  0.  1.]
 [ 0. 18.  0.]
 [ 0.  0. 13.]]
Sensitivity of Class 1 0.875
Specificity of Class 1 1.0
Sensitivity of Class 2 1.0
Specificity of Class 2 1.0
Sensitivity of Class 3 1.0
Specificity of Class 3 0.9615384615384616
(158, 9)
(40, 9)
Total accuracy:  0.875
Class 1 accuracy:  0.8421052631578947
Class 2 accuracy:  0.9166666666666666
Class 3 accuracy:  0.8888888888888888
[[16.  1.  2.]
 [ 1. 11.  0.]
 [ 1.  0.  8.]]
Sensitivity of Class 1 0.8421052631578947
Spe

In [ ]:
Cross_Validation(weights_stoch_L2_regu, 5, data, 5,alpha,iters,Lambda_,confusion_matrix_stoch_test_L2_regu)

(158, 9)
(40, 9)
Total accuracy:  0.95
Class 1 accuracy:  0.9090909090909091
Class 2 accuracy:  1.0
Class 3 accuracy:  0.9473684210526315
[[10.  1.  0.]
 [ 0. 10.  0.]
 [ 1.  0. 18.]]
Sensitivity of Class 1 0.9090909090909091
Specificity of Class 1 0.9655172413793104
Sensitivity of Class 2 1.0
Specificity of Class 2 0.9666666666666667
Sensitivity of Class 3 0.9473684210526315
Specificity of Class 3 1.0
(159, 9)
(39, 9)
Total accuracy:  0.9743589743589743
Class 1 accuracy:  0.875
Class 2 accuracy:  1.0
Class 3 accuracy:  1.0
[[ 7.  0.  1.]
 [ 0. 18.  0.]
 [ 0.  0. 13.]]
Sensitivity of Class 1 0.875
Specificity of Class 1 1.0
Sensitivity of Class 2 1.0
Specificity of Class 2 1.0
Sensitivity of Class 3 1.0
Specificity of Class 3 0.9615384615384616
(158, 9)
(40, 9)
Total accuracy:  0.875
Class 1 accuracy:  0.8421052631578947
Class 2 accuracy:  0.9166666666666666
Class 3 accuracy:  0.8888888888888888
[[16.  1.  2.]
 [ 1. 11.  0.]
 [ 1.  0.  8.]]
Sensitivity of Class 1 0.8421052631578947
Spe

In [ ]:
Cross_Validation(weights_mini_L2_regu, 5, data, 6,alpha,iters,Lambda_,confusion_matrix_mini_test_L2_regu)

(158, 9)
(40, 9)
Total accuracy:  0.95
Class 1 accuracy:  0.9090909090909091
Class 2 accuracy:  1.0
Class 3 accuracy:  0.9473684210526315
[[10.  1.  0.]
 [ 0. 10.  0.]
 [ 1.  0. 18.]]
Sensitivity of Class 1 0.9090909090909091
Specificity of Class 1 0.9655172413793104
Sensitivity of Class 2 1.0
Specificity of Class 2 0.9666666666666667
Sensitivity of Class 3 0.9473684210526315
Specificity of Class 3 1.0
(159, 9)
(39, 9)
Total accuracy:  0.9743589743589743
Class 1 accuracy:  0.875
Class 2 accuracy:  1.0
Class 3 accuracy:  1.0
[[ 7.  0.  1.]
 [ 0. 18.  0.]
 [ 0.  0. 13.]]
Sensitivity of Class 1 0.875
Specificity of Class 1 1.0
Sensitivity of Class 2 1.0
Specificity of Class 2 1.0
Sensitivity of Class 3 1.0
Specificity of Class 3 0.9615384615384616
(158, 9)
(40, 9)
Total accuracy:  0.875
Class 1 accuracy:  0.8421052631578947
Class 2 accuracy:  0.9166666666666666
Class 3 accuracy:  0.8888888888888888
[[16.  1.  2.]
 [ 1. 11.  0.]
 [ 1.  0.  8.]]
Sensitivity of Class 1 0.8421052631578947
Spe

In [ ]:
Cross_Validation(weights_batch_L1_regu, 5, data, 7,alpha,iters,Lambda_,confusion_matrix_batch_test_L1_regu)

(158, 9)
(40, 9)
Total accuracy:  0.95
Class 1 accuracy:  0.9090909090909091
Class 2 accuracy:  1.0
Class 3 accuracy:  0.9473684210526315
[[10.  1.  0.]
 [ 0. 10.  0.]
 [ 1.  0. 18.]]
Sensitivity of Class 1 0.9090909090909091
Specificity of Class 1 0.9655172413793104
Sensitivity of Class 2 1.0
Specificity of Class 2 0.9666666666666667
Sensitivity of Class 3 0.9473684210526315
Specificity of Class 3 1.0
(159, 9)
(39, 9)
Total accuracy:  0.9487179487179487
Class 1 accuracy:  0.75
Class 2 accuracy:  1.0
Class 3 accuracy:  1.0
[[ 6.  1.  1.]
 [ 0. 18.  0.]
 [ 0.  0. 13.]]
Sensitivity of Class 1 0.75
Specificity of Class 1 1.0
Sensitivity of Class 2 1.0
Specificity of Class 2 0.9523809523809523
Sensitivity of Class 3 1.0
Specificity of Class 3 0.9615384615384616
(158, 9)
(40, 9)
Total accuracy:  0.9
Class 1 accuracy:  0.8947368421052632
Class 2 accuracy:  0.9166666666666666
Class 3 accuracy:  0.8888888888888888
[[17.  0.  2.]
 [ 1. 11.  0.]
 [ 1.  0.  8.]]
Sensitivity of Class 1 0.894736842

In [ ]:
Cross_Validation(weights_stoch_L1_regu, 5, data, 8,alpha,iters,Lambda_,confusion_matrix_stoch_test_L1_regu)

(158, 9)
(40, 9)
Total accuracy:  0.95
Class 1 accuracy:  0.9090909090909091
Class 2 accuracy:  1.0
Class 3 accuracy:  0.9473684210526315
[[10.  1.  0.]
 [ 0. 10.  0.]
 [ 1.  0. 18.]]
Sensitivity of Class 1 0.9090909090909091
Specificity of Class 1 0.9655172413793104
Sensitivity of Class 2 1.0
Specificity of Class 2 0.9666666666666667
Sensitivity of Class 3 0.9473684210526315
Specificity of Class 3 1.0
(159, 9)
(39, 9)
Total accuracy:  0.9487179487179487
Class 1 accuracy:  0.75
Class 2 accuracy:  1.0
Class 3 accuracy:  1.0
[[ 6.  1.  1.]
 [ 0. 18.  0.]
 [ 0.  0. 13.]]
Sensitivity of Class 1 0.75
Specificity of Class 1 1.0
Sensitivity of Class 2 1.0
Specificity of Class 2 0.9523809523809523
Sensitivity of Class 3 1.0
Specificity of Class 3 0.9615384615384616
(158, 9)
(40, 9)
Total accuracy:  0.9
Class 1 accuracy:  0.8947368421052632
Class 2 accuracy:  0.9166666666666666
Class 3 accuracy:  0.8888888888888888
[[17.  0.  2.]
 [ 1. 11.  0.]
 [ 1.  0.  8.]]
Sensitivity of Class 1 0.894736842

In [ ]:
Cross_Validation(weights_mini_L1_regu, 5, data, 9,alpha,iters,Lambda_,confusion_matrix_mini_test_L1_regu)

(158, 9)
(40, 9)
Total accuracy:  0.975
Class 1 accuracy:  1.0
Class 2 accuracy:  1.0
Class 3 accuracy:  0.9473684210526315
[[11.  0.  0.]
 [ 0. 10.  0.]
 [ 1.  0. 18.]]
Sensitivity of Class 1 1.0
Specificity of Class 1 0.9655172413793104
Sensitivity of Class 2 1.0
Specificity of Class 2 1.0
Sensitivity of Class 3 0.9473684210526315
Specificity of Class 3 1.0
(159, 9)
(39, 9)
Total accuracy:  0.9487179487179487
Class 1 accuracy:  0.75
Class 2 accuracy:  1.0
Class 3 accuracy:  1.0
[[ 6.  1.  1.]
 [ 0. 18.  0.]
 [ 0.  0. 13.]]
Sensitivity of Class 1 0.75
Specificity of Class 1 1.0
Sensitivity of Class 2 1.0
Specificity of Class 2 0.9523809523809523
Sensitivity of Class 3 1.0
Specificity of Class 3 0.9615384615384616
(158, 9)
(40, 9)
Total accuracy:  0.9
Class 1 accuracy:  0.8947368421052632
Class 2 accuracy:  0.9166666666666666
Class 3 accuracy:  0.8888888888888888
[[17.  0.  2.]
 [ 1. 11.  0.]
 [ 1.  0.  8.]]
Sensitivity of Class 1 0.8947368421052632
Specificity of Class 1 0.90476190476

1 V ALL CLASSIFICATION

Initialising weights for all 9 models for 1 v all multiclass logistic regression

In [ ]:
weights_batch_no_regu_1vall=np.random.rand(3,8)
weights_stoch_no_regu_1vall=np.random.rand(3,8)
weights_mini_no_regu_1vall=np.random.rand(3,8) 
weights_batch_L2_regu_1vall=np.random.rand(3,8)
weights_stoch_L2_regu_1vall=np.random.rand(3,8)
weights_mini_L2_regu_1vall=np.random.rand(3,8)  
weights_batch_L1_regu_1vall=np.random.rand(3,8)
weights_stoch_L1_regu_1vall=np.random.rand(3,8)
weights_mini_L1_regu_1vall=np.random.rand(3,8)

Training of the 9 models for 1 v ALL logistic regression

In [ ]:
alpha=0.69
iters=20000
Lambda_=0.005

In [ ]:
confusion_matrix_batch_validation_no_regu_1vall = np.zeros((3,3))
confusion_matrix_batch_test_no_regu_1vall = np.zeros((3,3))
confusion_matrix_stoch_validation_no_regu_1vall = np.zeros((3,3))
confusion_matrix_stoch_test_no_regu_1vall = np.zeros((3,3))
confusion_matrix_mini_validation_no_regu_1vall = np.zeros((3,3))
confusion_matrix_mini_test_no_regu_1vall = np.zeros((3,3))
confusion_matrix_batch_validation_L2_regu_1vall = np.zeros((3,3))
confusion_matrix_batch_test_L2_regu_1vall = np.zeros((3,3))
confusion_matrix_stoch_validation_L2_regu_1vall = np.zeros((3,3))
confusion_matrix_stoch_test_L2_regu_1vall = np.zeros((3,3))
confusion_matrix_mini_validation_L2_regu_1vall = np.zeros((3,3))
confusion_matrix_mini_test_L2_regu_1vall = np.zeros((3,3))
confusion_matrix_batch_validation_L1_regu_1vall = np.zeros((3,3))
confusion_matrix_batch_test_L1_regu_1vall = np.zeros((3,3))
confusion_matrix_stoch_validation_L1_regu_1vall = np.zeros((3,3))
confusion_matrix_stoch_test_L1_regu_1vall = np.zeros((3,3))
confusion_matrix_mini_validation_L1_regu_1vall = np.zeros((3,3))
confusion_matrix_mini_test_L1_regu_1vall = np.zeros((3,3))

Testing accuracy of predictions

In [ ]:
def predict_1vall(test,weights,confusion_matrix): 
  
  for row in test:

      
      h = np.zeros(3)
      
      for i in range(3):
          h_ = np.dot(weights[i],row[:-1]) 
          h_ = sigmoid(h_) 
          h[i]=h_ 

          
      l = np.argmax(h)
      
      confusion_matrix[int(row[-1])-1, l] += 1
      

  c1 = confusion_matrix[0,0]/np.sum(confusion_matrix[0])
  c2 = confusion_matrix[1,1]/np.sum(confusion_matrix[1])
  c3 = confusion_matrix[2,2]/np.sum(confusion_matrix[2])
  d1=((confusion_matrix[1,1]+confusion_matrix[1,2]+confusion_matrix[2,1]+confusion_matrix[2,2])/
      (np.sum(confusion_matrix[1])+np.sum(confusion_matrix[2]))) 
  d2=((confusion_matrix[0,0]+confusion_matrix[0,2]+confusion_matrix[2,0]+confusion_matrix[2,2])/
      (np.sum(confusion_matrix[0])+np.sum(confusion_matrix[2]))) 
  d3=((confusion_matrix[0,0]+confusion_matrix[0,1]+confusion_matrix[1,0]+confusion_matrix[1,1])/
      (np.sum(confusion_matrix[0])+np.sum(confusion_matrix[1]))) 
  total_accuracy = (confusion_matrix[0,0] + confusion_matrix[1,1] + confusion_matrix[2,2])/np.sum(confusion_matrix)

  print("Total accuracy: ", total_accuracy)
  print("Class 1 accuracy: ", c1)
  print("Class 2 accuracy: ", c2)
  print("Class 3 accuracy: ", c3)
  print(confusion_matrix) 
  return c1,c2,c3,d1,d2,d3

In [ ]:
def Cross_validation_1vall(w, k, examples, c,alpha,iters,Lambda_,confusion_matrix):
     m=examples.shape[0]
     pp=np.ones([m,1])
     examples=np.append(pp,examples,axis=1) 
     for fold in range(0, k):
            train, test_set = partition(examples, fold, k)
            
            #1st model
            for i in range(3):  
                
                X = train.copy() #copy of the training samples
                for row in X:
                    if row[-1] == i+1:
                        row[-1] = 1
                    else:
                        row[-1] = 0  
                
                X_train=X[:,0:8]
                y_train=X[:,8]
                if (c==1):         
                  w[i]=batch_gradient_descent_no_regu(X_train,y_train,w[i],alpha,iters)  
                elif (c==2):
                  #2nd model
                  w[i]=stochastic_gradient_descent_no_regu(X_train,y_train,w[i],alpha,iters) 
                elif (c==3): #3rd model
                  w[i]=minibatch_gradient_descent_no_regu(X_train,y_train,w[i],alpha,iters,15)
                elif (c==4): #4th model  
                  w[i]=batch_gradient_descent_L2_regu(X_train,y_train,w[i],alpha,iters,Lambda_)
                elif (c==5): #5th model
                  w[i]=stochastic_gradient_descent_L2_regu(X_train,y_train,w[i],alpha,iters,Lambda_)
                elif (c==6): #6th model 
                  w[i]=minibatch_gradient_descent_L2_regu(X_train,y_train,w[i],alpha,iters,15,Lambda_) 
                elif (c==7): #7th model
                  w[i]=batch_gradient_descent_L1_regu(X_train,y_train,w[i],alpha,iters,Lambda_)
                elif (c==8): #8th model 
                  w[i]=stochastic_gradient_descent_L1_regu(X_train,y_train,w[i],alpha,iters,Lambda_)
                elif (c==9): #9th model 
                  w[i]=minibatch_gradient_descent_L1_regu(X_train,y_train,w[i],alpha,iters,15,Lambda_)        
                 
            sens1,sens2,sens3,spec1,spec2,spec3=predict_1vall(test_set,w,confusion_matrix)   
            print("Sensitivity of Class 1",sens1)
            print("Specificity of Class 1",spec1) 
            print("Sensitivity of Class 2",sens2)
            print("Specificity of Class 2",spec2) 
            print("Sensitivity of Class 3",sens3)
            print("Specificity of Class 3",spec3)
            confusion_matrix=np.zeros((3,3))    

In [ ]:
Cross_validation_1vall(weights_batch_no_regu_1vall,5,data,1,alpha,iters,Lambda_,confusion_matrix_batch_test_no_regu_1vall)

(158, 9)
(40, 9)
Total accuracy:  0.5
Class 1 accuracy:  0.5
Class 2 accuracy:  0.5
Class 3 accuracy:  0.5
[[11. 11.  0.]
 [ 0. 10. 10.]
 [19.  0. 19.]]
Sensitivity of Class 1 0.5
Specificity of Class 1 0.6724137931034483
Sensitivity of Class 2 0.5
Specificity of Class 2 0.8166666666666667
Sensitivity of Class 3 0.5
Specificity of Class 3 0.7619047619047619
(159, 9)
(39, 9)
Total accuracy:  0.9743589743589743
Class 1 accuracy:  0.875
Class 2 accuracy:  1.0
Class 3 accuracy:  1.0
[[ 7.  0.  1.]
 [ 0. 18.  0.]
 [ 0.  0. 13.]]
Sensitivity of Class 1 0.875
Specificity of Class 1 1.0
Sensitivity of Class 2 1.0
Specificity of Class 2 1.0
Sensitivity of Class 3 1.0
Specificity of Class 3 0.9615384615384616
(158, 9)
(40, 9)
Total accuracy:  0.95
Class 1 accuracy:  1.0
Class 2 accuracy:  0.9166666666666666
Class 3 accuracy:  0.8888888888888888
[[19.  0.  0.]
 [ 1. 11.  0.]
 [ 1.  0.  8.]]
Sensitivity of Class 1 1.0
Specificity of Class 1 0.9047619047619048
Sensitivity of Class 2 0.9166666666666

In [ ]:
Cross_validation_1vall(weights_stoch_no_regu_1vall,5,data,2,alpha,iters,Lambda_,confusion_matrix_stoch_test_no_regu_1vall)

(158, 9)
(40, 9)
Total accuracy:  1.0
Class 1 accuracy:  1.0
Class 2 accuracy:  1.0
Class 3 accuracy:  1.0
[[11.  0.  0.]
 [ 0. 10.  0.]
 [ 0.  0. 19.]]
Sensitivity of Class 1 1.0
Specificity of Class 1 1.0
Sensitivity of Class 2 1.0
Specificity of Class 2 1.0
Sensitivity of Class 3 1.0
Specificity of Class 3 1.0
(159, 9)
(39, 9)
Total accuracy:  0.9743589743589743
Class 1 accuracy:  0.875
Class 2 accuracy:  1.0
Class 3 accuracy:  1.0
[[ 7.  0.  1.]
 [ 0. 18.  0.]
 [ 0.  0. 13.]]
Sensitivity of Class 1 0.875
Specificity of Class 1 1.0
Sensitivity of Class 2 1.0
Specificity of Class 2 1.0
Sensitivity of Class 3 1.0
Specificity of Class 3 0.9615384615384616
(158, 9)
(40, 9)
Total accuracy:  0.95
Class 1 accuracy:  1.0
Class 2 accuracy:  0.9166666666666666
Class 3 accuracy:  0.8888888888888888
[[19.  0.  0.]
 [ 1. 11.  0.]
 [ 1.  0.  8.]]
Sensitivity of Class 1 1.0
Specificity of Class 1 0.9047619047619048
Sensitivity of Class 2 0.9166666666666666
Specificity of Class 2 1.0
Sensitivity of

In [ ]:
Cross_validation_1vall(weights_mini_no_regu_1vall,5,data,3,alpha,iters,Lambda_,confusion_matrix_mini_test_no_regu_1vall)

(158, 9)
(40, 9)
Total accuracy:  1.0
Class 1 accuracy:  1.0
Class 2 accuracy:  1.0
Class 3 accuracy:  1.0
[[11.  0.  0.]
 [ 0. 10.  0.]
 [ 0.  0. 19.]]
Sensitivity of Class 1 1.0
Specificity of Class 1 1.0
Sensitivity of Class 2 1.0
Specificity of Class 2 1.0
Sensitivity of Class 3 1.0
Specificity of Class 3 1.0
(159, 9)
(39, 9)
Total accuracy:  0.9743589743589743
Class 1 accuracy:  0.875
Class 2 accuracy:  1.0
Class 3 accuracy:  1.0
[[ 7.  0.  1.]
 [ 0. 18.  0.]
 [ 0.  0. 13.]]
Sensitivity of Class 1 0.875
Specificity of Class 1 1.0
Sensitivity of Class 2 1.0
Specificity of Class 2 1.0
Sensitivity of Class 3 1.0
Specificity of Class 3 0.9615384615384616
(158, 9)
(40, 9)
Total accuracy:  0.95
Class 1 accuracy:  1.0
Class 2 accuracy:  0.9166666666666666
Class 3 accuracy:  0.8888888888888888
[[19.  0.  0.]
 [ 1. 11.  0.]
 [ 1.  0.  8.]]
Sensitivity of Class 1 1.0
Specificity of Class 1 0.9047619047619048
Sensitivity of Class 2 0.9166666666666666
Specificity of Class 2 1.0
Sensitivity of

In [ ]:
Cross_validation_1vall(weights_batch_L2_regu_1vall,5,data,4,alpha,iters,Lambda_,confusion_matrix_batch_test_L2_regu_1vall)

(158, 9)
(40, 9)
Total accuracy:  0.925
Class 1 accuracy:  0.8181818181818182
Class 2 accuracy:  1.0
Class 3 accuracy:  0.9473684210526315
[[ 9.  2.  0.]
 [ 0. 10.  0.]
 [ 1.  0. 18.]]
Sensitivity of Class 1 0.8181818181818182
Specificity of Class 1 0.9655172413793104
Sensitivity of Class 2 1.0
Specificity of Class 2 0.9333333333333333
Sensitivity of Class 3 0.9473684210526315
Specificity of Class 3 1.0
(159, 9)
(39, 9)
Total accuracy:  0.9487179487179487
Class 1 accuracy:  0.875
Class 2 accuracy:  1.0
Class 3 accuracy:  0.9230769230769231
[[ 7.  1.  0.]
 [ 0. 18.  0.]
 [ 1.  0. 12.]]
Sensitivity of Class 1 0.875
Specificity of Class 1 0.967741935483871
Sensitivity of Class 2 1.0
Specificity of Class 2 0.9523809523809523
Sensitivity of Class 3 0.9230769230769231
Specificity of Class 3 1.0
(158, 9)
(40, 9)
Total accuracy:  0.825
Class 1 accuracy:  0.7368421052631579
Class 2 accuracy:  0.9166666666666666
Class 3 accuracy:  0.8888888888888888
[[14.  1.  4.]
 [ 1. 11.  0.]
 [ 1.  0.  8.]]


In [ ]:
Cross_validation_1vall(weights_stoch_L2_regu_1vall,5,data,5,alpha,iters,Lambda_,confusion_matrix_stoch_test_L2_regu_1vall)

(158, 9)
(40, 9)
Total accuracy:  0.95
Class 1 accuracy:  0.9090909090909091
Class 2 accuracy:  1.0
Class 3 accuracy:  0.9473684210526315
[[10.  1.  0.]
 [ 0. 10.  0.]
 [ 1.  0. 18.]]
Sensitivity of Class 1 0.9090909090909091
Specificity of Class 1 0.9655172413793104
Sensitivity of Class 2 1.0
Specificity of Class 2 0.9666666666666667
Sensitivity of Class 3 0.9473684210526315
Specificity of Class 3 1.0
(159, 9)
(39, 9)
Total accuracy:  0.9487179487179487
Class 1 accuracy:  0.875
Class 2 accuracy:  1.0
Class 3 accuracy:  0.9230769230769231
[[ 7.  1.  0.]
 [ 0. 18.  0.]
 [ 1.  0. 12.]]
Sensitivity of Class 1 0.875
Specificity of Class 1 0.967741935483871
Sensitivity of Class 2 1.0
Specificity of Class 2 0.9523809523809523
Sensitivity of Class 3 0.9230769230769231
Specificity of Class 3 1.0
(158, 9)
(40, 9)
Total accuracy:  0.85
Class 1 accuracy:  0.7894736842105263
Class 2 accuracy:  0.9166666666666666
Class 3 accuracy:  0.8888888888888888
[[15.  0.  4.]
 [ 1. 11.  0.]
 [ 1.  0.  8.]]
Se

In [ ]:
Cross_validation_1vall(weights_mini_L2_regu_1vall,5,data,6,alpha,iters,Lambda_,confusion_matrix_mini_test_L2_regu_1vall)

(158, 9)
(40, 9)
Total accuracy:  0.95
Class 1 accuracy:  0.8181818181818182
Class 2 accuracy:  1.0
Class 3 accuracy:  1.0
[[ 9.  2.  0.]
 [ 0. 10.  0.]
 [ 0.  0. 19.]]
Sensitivity of Class 1 0.8181818181818182
Specificity of Class 1 1.0
Sensitivity of Class 2 1.0
Specificity of Class 2 0.9333333333333333
Sensitivity of Class 3 1.0
Specificity of Class 3 1.0
(159, 9)
(39, 9)
Total accuracy:  0.9487179487179487
Class 1 accuracy:  0.875
Class 2 accuracy:  1.0
Class 3 accuracy:  0.9230769230769231
[[ 7.  1.  0.]
 [ 0. 18.  0.]
 [ 1.  0. 12.]]
Sensitivity of Class 1 0.875
Specificity of Class 1 0.967741935483871
Sensitivity of Class 2 1.0
Specificity of Class 2 0.9523809523809523
Sensitivity of Class 3 0.9230769230769231
Specificity of Class 3 1.0
(158, 9)
(40, 9)
Total accuracy:  0.825
Class 1 accuracy:  0.7368421052631579
Class 2 accuracy:  0.9166666666666666
Class 3 accuracy:  0.8888888888888888
[[14.  1.  4.]
 [ 1. 11.  0.]
 [ 1.  0.  8.]]
Sensitivity of Class 1 0.7368421052631579
Spec

In [ ]:
Cross_validation_1vall(weights_batch_L1_regu_1vall,5,data,7,alpha,iters,Lambda_,confusion_matrix_batch_test_L1_regu_1vall)

(158, 9)
(40, 9)
Total accuracy:  1.0
Class 1 accuracy:  1.0
Class 2 accuracy:  1.0
Class 3 accuracy:  1.0
[[11.  0.  0.]
 [ 0. 10.  0.]
 [ 0.  0. 19.]]
Sensitivity of Class 1 1.0
Specificity of Class 1 1.0
Sensitivity of Class 2 1.0
Specificity of Class 2 1.0
Sensitivity of Class 3 1.0
Specificity of Class 3 1.0
(159, 9)
(39, 9)
Total accuracy:  0.9743589743589743
Class 1 accuracy:  0.875
Class 2 accuracy:  1.0
Class 3 accuracy:  1.0
[[ 7.  1.  0.]
 [ 0. 18.  0.]
 [ 0.  0. 13.]]
Sensitivity of Class 1 0.875
Specificity of Class 1 1.0
Sensitivity of Class 2 1.0
Specificity of Class 2 0.9523809523809523
Sensitivity of Class 3 1.0
Specificity of Class 3 1.0
(158, 9)
(40, 9)
Total accuracy:  0.9
Class 1 accuracy:  0.8947368421052632
Class 2 accuracy:  0.9166666666666666
Class 3 accuracy:  0.8888888888888888
[[17.  0.  2.]
 [ 1. 11.  0.]
 [ 1.  0.  8.]]
Sensitivity of Class 1 0.8947368421052632
Specificity of Class 1 0.9047619047619048
Sensitivity of Class 2 0.9166666666666666
Specificity 

In [ ]:
Cross_validation_1vall(weights_stoch_L1_regu_1vall,5,data,8,alpha,iters,Lambda_,confusion_matrix_stoch_test_L1_regu_1vall)

(158, 9)
(40, 9)
Total accuracy:  1.0
Class 1 accuracy:  1.0
Class 2 accuracy:  1.0
Class 3 accuracy:  1.0
[[11.  0.  0.]
 [ 0. 10.  0.]
 [ 0.  0. 19.]]
Sensitivity of Class 1 1.0
Specificity of Class 1 1.0
Sensitivity of Class 2 1.0
Specificity of Class 2 1.0
Sensitivity of Class 3 1.0
Specificity of Class 3 1.0
(159, 9)
(39, 9)
Total accuracy:  0.9743589743589743
Class 1 accuracy:  0.875
Class 2 accuracy:  1.0
Class 3 accuracy:  1.0
[[ 7.  1.  0.]
 [ 0. 18.  0.]
 [ 0.  0. 13.]]
Sensitivity of Class 1 0.875
Specificity of Class 1 1.0
Sensitivity of Class 2 1.0
Specificity of Class 2 0.9523809523809523
Sensitivity of Class 3 1.0
Specificity of Class 3 1.0
(158, 9)
(40, 9)
Total accuracy:  0.925
Class 1 accuracy:  0.9473684210526315
Class 2 accuracy:  0.9166666666666666
Class 3 accuracy:  0.8888888888888888
[[18.  0.  1.]
 [ 1. 11.  0.]
 [ 1.  0.  8.]]
Sensitivity of Class 1 0.9473684210526315
Specificity of Class 1 0.9047619047619048
Sensitivity of Class 2 0.9166666666666666
Specificit

In [ ]:
Cross_validation_1vall(weights_mini_L1_regu_1vall,5,data,9,alpha,iters,Lambda_,confusion_matrix_mini_test_L1_regu_1vall)

(158, 9)
(40, 9)
Total accuracy:  1.0
Class 1 accuracy:  1.0
Class 2 accuracy:  1.0
Class 3 accuracy:  1.0
[[11.  0.  0.]
 [ 0. 10.  0.]
 [ 0.  0. 19.]]
Sensitivity of Class 1 1.0
Specificity of Class 1 1.0
Sensitivity of Class 2 1.0
Specificity of Class 2 1.0
Sensitivity of Class 3 1.0
Specificity of Class 3 1.0
(159, 9)
(39, 9)
Total accuracy:  0.9743589743589743
Class 1 accuracy:  0.875
Class 2 accuracy:  1.0
Class 3 accuracy:  1.0
[[ 7.  1.  0.]
 [ 0. 18.  0.]
 [ 0.  0. 13.]]
Sensitivity of Class 1 0.875
Specificity of Class 1 1.0
Sensitivity of Class 2 1.0
Specificity of Class 2 0.9523809523809523
Sensitivity of Class 3 1.0
Specificity of Class 3 1.0
(158, 9)
(40, 9)
Total accuracy:  0.9
Class 1 accuracy:  0.8947368421052632
Class 2 accuracy:  0.9166666666666666
Class 3 accuracy:  0.8888888888888888
[[17.  0.  2.]
 [ 1. 11.  0.]
 [ 1.  0.  8.]]
Sensitivity of Class 1 0.8947368421052632
Specificity of Class 1 0.9047619047619048
Sensitivity of Class 2 0.9166666666666666
Specificity 